#!/bin/sh

FLAGS=""
if [[ ! -z "${PLUGIN_DEPTH}" ]]; then
	FLAGS="--depth=${PLUGIN_DEPTH}"
fi

if [ ! -d .git ]; then
	git init
	git remote add origin ${DRONE_REMOTE_URL}
fi

set -e
set -x

if [ -n "${PLUGIN_FETCHREFS}" ]; then
    for ref_name in $( echo "${PLUGIN_FETCHREFS}" | tr ',' ' ' ) ; do
        git fetch ${FLAGS} origin +${ref_name}:
    done
    git checkout ${DRONE_COMMIT_SHA} \
        -b ${PLUGIN_CHECKOUTBRANCH:-"${DRONE_COMMIT_BRANCH}"}
else
    git fetch ${FLAGS} origin +refs/heads/${DRONE_COMMIT_BRANCH}:
    git checkout ${DRONE_COMMIT_SHA} -b ${DRONE_COMMIT_BRANCH}
fi



